<?xml version="1.0"?>

<!-- Please note that this URDF will _not_ load in gazebo -->

<robot xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface"
       xmlns:xacro="http://ros.org/wiki/xacro"
       name="pioneer3at">


  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find pioneer3at_description)/urdf/pioneer3at.gazebo" /> 
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find pioneer3at_description)/urdf/pioneer3at_material.xacro" />


<xacro:property name="height_base" value="0.354" /> 
<xacro:property name="width_base" value="0.49" /> 
<xacro:property name="h_base" value="0.28" /> 
<xacro:property name="d_base" value="0.25" /> 

<!-- (w)idth: c  
     (d)epth: a 
     (h)eight: b

Ix = 1/12 m (d^2 + h^2)
Iy = 1/12 m (h^2 + w^2)
Iz = 1/12 m (w^2 + d^2)
 -->
<xacro:macro name="cube_intertia" params="xyz rpy mass w h d">
    <origin xyz="${xyz}" rpy="${rpy}"/>
    <mass value="${mass}"/>
    <inertia ixx="1e-3" ixy="0.0" ixz="0.0" iyy="1e-3" iyz="0.0" izz="1e-3" />-->
  <!--  <inertia ixx="1/12 * ${mass} * (${d^2} + ${h^2})" ixy="0.0" ixz="0.0" iyy="1/12 * ${mass} * (${h^2} + ${w^2})" iyz="0.0" izz="1/12 * ${mass} * (${w^2} + ${d^2})" />
			<xacro:cube_intertia xyz="0 0 ${height_base/2}" rpy="0 0 0" mass="14.0" w="0.49" h="0.28" d="0.25"/>-->
</xacro:macro>

  <macro name="cylinder_inertia" params="m r h">
    <inertia  ixx="${m*(3*r*r+h*h)/12}" ixy = "0" ixz = "0"
              iyy="${m*(3*r*r+h*h)/12}" iyz = "0"
              izz="${m*r*r/2}" /> 
  </macro>

<!-- Chassis -->
	<link name="Pioneer3AT/base_link">
		<visual>
			<origin xyz="0 0 ${height_base/2}" rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://pioneer3at_description/meshes/chassis.stl"/>
			</geometry>
			<material name="ChassisRed"/>

		</visual>

  		<inertial>
    			<origin xyz="0 0 ${height_base/2}" rpy="0 0 0"/>
    			<mass value="14"/>
          		<inertia ixx="${1/12 * 14 * (0.25*0.25 + 0.49*0.49)}" ixy="0.0" ixz="0.0" iyy="${1/12 * 14 * (0.28*0.28 + 0.49*0.49)}" iyz="0.0" izz="${1/12 * 14 * (0.25*0.25 + 0.49*0.49)}" />
        	</inertial>

		<collision>
      			<origin xyz="0 0 ${height_base/2}" rpy="0 0 0"/>
      			<geometry>
		 		<box size="0.49 0.28 0.25"/>
      			</geometry>
    		</collision>

	</link>

<!-- Top -->
	<link name="top_plate">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://pioneer3at_description/meshes/top.stl"/>
			</geometry>
			<material name="TopBlack"/>
		</visual>

  		<inertial>
      			<origin xyz="0 0 0" rpy="0 0 0"/>
	        	<mass value="0.1"/>
          		<inertia ixx="1e-3" ixy="0.0" ixz="0.0" iyy="1e-3" iyz="0.0" izz="1e-3" />
        	</inertial>

		<collision>
      			<origin xyz="0 0 0" rpy="0 0 0"/>
      			<geometry>
				<mesh filename="package://pioneer3at_description/meshes/top.stl"/>
      			</geometry>
    		</collision>

	</link>

	<joint name="base_top_joint" type="fixed">
		<origin xyz="0.003 0 0.274" rpy="0 0 0"/>
		<parent link="Pioneer3AT/base_link"/>
		<child link="top_plate"/>
	</joint>


<!-- Axle~Hub~Wheel  -->
  <xacro:macro name="wheel" params="prefix rx ry">
	  
	<link name="${prefix}_axle">
      		<visual>
        		<origin xyz="0 0 0" rpy="0 0 0"/>
        		<geometry>
	        		<mesh filename="package://pioneer3at_description/meshes/axle.stl"/>
        		</geometry>
        		<material name="AxleGrey"/>
      		</visual>

  		<inertial>
      			<origin xyz="0 0 0" rpy="0 0 0"/>
	        	<mass value="0.05"/>
          		<inertia ixx="1e-6" ixy="0.0" ixz="0.0" iyy="1e-6" iyz="0.0" izz="1e-6" />
        	</inertial>

		<collision>
      			<origin xyz="0 0 0" rpy="0 0 0"/>
      			<geometry>
        			<mesh filename="package://pioneer3at_description/meshes/axle.stl"/>
      			</geometry>
    		</collision>
	  </link>

	  <joint name="${prefix}_axle_joint" type="continuous">
		  <origin xyz="${rx*0.135} ${ry*0.156} 0.111" rpy="0 0 0"/>
		  <parent link="Pioneer3AT/base_link"/>
		  <child link="${prefix}_axle"/>
		  <axis xyz="0 1 0" />
	  </joint>

	<link name="${prefix}_hub">
		<visual>
			<origin xyz="0 0 0" rpy="${ry * 1.57 - 1.57} 0 0"/>
		    	<geometry>
				<mesh filename="package://pioneer3at_description/meshes/hub.stl"/>
		    	</geometry>
		    	<material name="HubcapYellow"/>
	    	</visual>

  		<inertial>
      			<origin xyz="0 0 0" rpy="0 0 0"/>
	        	<mass value="0.05"/>
          		<inertia ixx="1e-6" ixy="0.0" ixz="0.0" iyy="1e-6" iyz="0.0" izz="1e-6" />
        	</inertial>

		<collision>
      			<origin xyz="0 0 0" rpy="0 0 0"/>
      			<geometry>
        			<mesh filename="package://pioneer3at_description/meshes/hub.stl"/>
      			</geometry>
    		</collision>
	</link>

	<joint name="${prefix}_hub_joint" type="fixed">
		<origin xyz="0 ${ry*0.041} 0" rpy="0 0 0"/>
		<parent link="${prefix}_axle"/>
		<child link="${prefix}_hub"/>
	 </joint>

	<link name="${prefix}_wheel">
		<visual>
			<origin xyz="0 0 0" rpy="0 0 0"/>
			<geometry>
				<mesh filename="package://pioneer3at_description/meshes/wheel.stl"/>
			</geometry>
			<material name="WheelBlack"/>
		</visual>

  		<inertial>
			<origin xyz="0 0 0" rpy="0 0 0"/>
	        	<mass value="1"/>
        		<cylinder_inertia  m="1" r="0.1" h="0.11" />
        	</inertial>


		<collision>
			 <origin xyz="0 0 0" rpy="1.570700 0.000000 0.000000"/>
                	<geometry>
 			 <cylinder length="0.11" radius="0.1"/>
                	</geometry>
    		</collision>
	</link>

	<joint name="${prefix}_wheel_joint" type="fixed">
		  <origin xyz="0 0 0" rpy="0 0 0"/>
		  <parent link="${prefix}_hub"/>
		  <child link="${prefix}_wheel"/>
	</joint>
  </xacro:macro>


  <xacro:wheel prefix="front_left"  rx="1"  ry="1" />
  <xacro:wheel prefix="front_right" rx="1"  ry="-1"/>
  <xacro:wheel prefix="rear_left"   rx="-1" ry="1" />
  <xacro:wheel prefix="rear_right"  rx="-1" ry="-1"/>
  
  
<!-- Sonar -->
<!-- Front Sonar -->
<link name="front_sonar">
	<visual>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<mesh filename="package://pioneer3at_description/meshes/front_sonar.stl"/>
		</geometry>
		<material name="SonarYellow"/> 
	</visual>

  		<inertial>
      			<origin xyz="0 0 0" rpy="0 0 0"/>
	        	<mass value="0.1"/>
          		<inertia ixx="1e-3" ixy="0.0" ixz="0.0" iyy="1e-3" iyz="0.0" izz="1e-3" />
        	</inertial>

		<collision>
      			<origin xyz="0 0 0" rpy="0 0 0"/>
      			<geometry>
				<mesh filename="package://pioneer3at_description/meshes/front_sonar.stl"/>
      			</geometry>
    		</collision>
</link>

<joint name="front_sonar_joint" type="fixed">
	<origin xyz="0.193 0 0.25" rpy="0 0 0"/>
	<parent link="Pioneer3AT/base_link"/>
	<child link="front_sonar"/>
</joint>

<!-- Rear Sonar -->
<link name="rear_sonar">
	<visual>
		<origin xyz="0 0 0" rpy="0 0 0"/>
		<geometry>
			<mesh filename="package://pioneer3at_description/meshes/back_sonar.stl"/>
		</geometry>
		<material name="SonarYellow"/>
	</visual>
</link>

<joint name="rear_sonar_joint" type="fixed">
	<origin xyz="-0.187 0 0.247" rpy="0 0 0"/>
	<parent link="Pioneer3AT/base_link"/>
	<child link="rear_sonar"/>
</joint>


  <joint name="hokuyo_joint" type="fixed">
    <axis xyz="0 1 0" />
    <origin xyz="${width_base/2 * 0.8} 0 0.035" rpy="0 0 0"/>
    <parent link="top_plate"/>
    <child link="hokuyo_link"/>
  </joint>


  <link name="hokuyo_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.1 0.1 0.1"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="package://pioneer3at_description/meshes/hokuyo.dae"/>
      </geometry>
    </visual>

    <inertial>
      <mass value="1e-5" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6" />
    </inertial>
  </link>


	
  <xacro:macro name="Sonar" params="id px py rz">
	  <link name="Sonar_${id}">
      <visual>
	      <origin xyz="0 0 0" rpy="0 1.57 0"/>
	      <geometry>
		      <cylinder radius="0.01" length="0.005"/>
	      </geometry>
	      <material name="SonarGold"/>
      </visual>
	  </link>

	  <joint name="Sonar_${id}_joint" type="fixed">
		  <origin xyz="${px} ${py} 0.25" rpy="0 0 ${rz}"/>
		  <parent link="Pioneer3AT/base_link"/>
		  <child link="Sonar_${id}"/>
	  </joint>
  </xacro:macro>
  
<!-- Sonar offsets came from p2os_driver robot_params.cc -->
<!-- Not used, a lot of TF clutter
  <xacro:Sonar id="1"  px="0.145"  py="0.13"   rz="1.5705"/>
  <xacro:Sonar id="2"  px="0.185"  py="0.115"  rz="0.8725"/>
  <xacro:Sonar id="3"  px="0.22"   py="0.08"   rz="0.5235"/>
  <xacro:Sonar id="4"  px="0.24"   py="0.025"  rz="0.1745"/>
  <xacro:Sonar id="5"  px="0.24"   py="-0.025" rz="-0.1745"/>
  <xacro:Sonar id="6"  px="0.22"   py="-0.08"  rz="-0.5235"/>
  <xacro:Sonar id="7"  px="0.185"  py="-0.115" rz="-0.8725"/>
  <xacro:Sonar id="8"  px="0.145"  py="-0.13"  rz="-1.5705"/>
  <xacro:Sonar id="9"  px="-0.145" py="-0.13"  rz="-1.5705"/>
  <xacro:Sonar id="10" px="-0.185" py="-0.115" rz="-2.2685"/>
  <xacro:Sonar id="11" px="-0.22"  py="-0.08"  rz="-2.6175"/>
  <xacro:Sonar id="12" px="-0.24"  py="-0.025" rz="-2.9665"/>
  <xacro:Sonar id="13" px="-0.24"  py="0.025"  rz="2.9665"/>
  <xacro:Sonar id="14" px="-0.22"  py="0.08"   rz="2.6175"/>
  <xacro:Sonar id="15" px="-0.185" py="0.115"  rz="2.2685"/>
  <xacro:Sonar id="16" px="-0.145" py="0.13"   rz="1.5705"/>
-->



</robot>


